Added build_test_java

diff --git a/.github/workflows/build_test_java.yaml b/.github/workflows/build_test_java.yaml
--- a/.github/workflows/build_test_java.yaml
+++ b/.github/workflows/build_test_java.yaml
@@ -1,32 +1,18 @@
-name: Java CI
+name: Java CI (4Test)
 
 on:
   push:
-    branches:
-      - main
-    tags:
-      - 'v*'
+    paths:
+      - 'common/**'
+      - 'java/**'
 
 permissions:
   contents: read
 
 jobs:
-  check-version-with-tag:
-    name: Check Version
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Check Version With Tag
-        run: |
-          chmod +x ./.github/scripts/check_version_by.sh
-          ./.github/scripts/check_version_by.sh $(grep -oE "^version = .*$" "./java/java/lib/build.gradle" | sed -ne "s/^version = \"\(.*\)\"$/\1/p")
-        shell: bash
-        working-directory: ./
-
   build:
     name: Build ${{ matrix.settings.target }}
     runs-on: ${{ matrix.settings.host }}
-    needs: [ check-version-with-tag ]
     strategy:
       matrix:
         settings:
@@ -78,9 +64,11 @@ jobs:
           path: ./artifacts/${{ matrix.settings.target_name }}
 
   publish:
-    name: Publish
+    name: Push
     needs: [ build ]
     runs-on: ubuntu-latest
+    env:
+      BRANCH: "test"
     steps:
       - uses: actions/checkout@v4
       - name: Download all artifacts
@@ -90,7 +78,7 @@ jobs:
           merge-multiple: true
       - name: Clone, Update, Push
         run: |
-          branch="main"
+          branch=${{env.BRANCH}}
           echo "Cloning..."
           mkdir target_repo && cd target_repo
           git clone -b "$branch" https://github.com/datatower-ai/dt-java-sdk.git
@@ -115,7 +103,34 @@ jobs:
           git config user.email "<>"
           git config url."https://${{ secrets.SERVER_SDK_JAVA_TOKEN }}@github.com/".insteadOf "https://github.com/"
           git add .
-          git commit -m "GitHub Action Bot: Syncing with v$version"
-          git tag "$version"
-          git push -f origin "$branch" --tags
+          timestamp=$(date +%s)
+          git commit -m "GitHub Action Bot: Syncing with v$version (Test, $timestamp)"
+          git push -f origin "$branch"
+        shell: bash
+      - name: Trigger build SNAPSHOT
+        if: always()
+        run: |
+          branch=${{env.BRANCH}}
+          echo "on branch: $branch"
+          PACKAGE_URL="https://jitpack.io/com/github/datatower-ai/dt-java-sdk/$branch-SNAPSHOT/"
+          
+          count=1
+          file_count=0
+          max_try=3
+          until [[ $count -gt $max_try ]] || [[ $file_count -gt 1 ]]; do
+            echo "Attempt ${count}/${max_try}"
+            FILES=$(curl -sS -m 180 ${PACKAGE_URL})
+            file_count=$(echo $FILES | wc -w | xargs)
+            let count+=1
+            sleep 5
+          done
+          
+          echo "=> ${PACKAGE_URL}build.log"
+          if [[ file_count -gt 1 ]]; then
+            echo "Finished!"
+            exit 0
+          else
+            echo "Failed!"
+            exit 1
+          fi
         shell: bash
